export async function GET(){
    try{

    }catch(error){
        throw new Error('Error in Get')
    }
}